conn system/java1019;
drop user PET cascade;
create user pet identified by java;
grant connect, resource to pet;
conn pet/java;

/* 멤버 */
CREATE TABLE MEMBER(
    MEMBER_NUMBER NUMBER(6),
    MEMBER_EMAIL VARCHAR2(50),
    MEMEBER_PW VARCHAR2(30),
    MEMBER_NAME VARCHAR2(20),
    MEMBER_ADRESS VARCHAR2(100),
    MEMBER_DATE DATE DEFAULT SYSDATE
);
alter table MEMBER add constraint MEMBER_PK primary key(MEMBER_NUMBER);
create sequence MEMBER_SEQ increment by 1 start with 1 nocache;

/* 팔로우 */
CREATE TABLE FOLLOW(
	MEMBER_NUMBER NUMBER(6) CONSTRAINT FOLLOW_FK1 REFERENCES MEMBER(MEMBER_NUMBER),
    FOLLOW_NUMBER NUMBER(6) CONSTRAINT FOLLOW_FK2 REFERENCES MEMBER(MEMBER_NUMBER),
	FOLLOW_TYPE VARCHAR2(10)
);

/* 마이페이지 */
CREATE TABLE PET_MYPAGE(
	MEMBER_NUMBER NUMBER(6),
    PET_NAME VARCHAR2(20) NOT NULL,
    PET_SEX VARCHAR2(20) NOT NULL,
	PET_AGE DATE,
    PET_WALKAREA VARCHAR2(50) NOT NULL,
	PET_WALKPOINT NUMBER,
	PET_FNAME VARCHAR2(300),
	PET_OFNAME VARCHAR2(300),
	PET_FSIZE NUMBER
);
alter table PET_MYPAGE add constraint PET_MYPAGE_PK primary key(MEMBER_NUMBER);
alter table PET_MYPAGE add constraint PET_MYPAGE_MEMBER_FK foreign key(MEMBER_NUMBER) references MEMBER on delete cascade;

/* 메세지 */
CREATE TABLE MEMBER_MESSAGE(
    MEMBER_NUMBER NUMBER(6),
    SENDER_NAME VARCHAR2(20),
    MSG_CONTENT VARCHAR2(1000),
    MSG_DATE DATE
);
alter table MEMBER_MESSAGE add constraint MEMBER_MESSAGE_PK primary key(MEMBER_NUMBER);
alter table MEMBER_MESSAGE add constraint MEMBER_MESSAGE_MEMBER_FK foreign key(MEMBER_NUMBER) references MEMBER on delete cascade;

/* 카테고리 */
create table CATGO(
	CATGO_CODE NUMBER,
	CATGO_NAME VARCHAR2(20)
);
alter table CATGO add constraint CATGO_PK primary key(CATGO_CODE);
create sequence CATGO_SEQ increment by 1 start with 1 nocache;

/* 쇼핑  */
create table PRODUCT(
   PRODUCT_CODE NUMBER,
   CATGO_CODE NUMBER CONSTRAINT PRODUCT_FK REFERENCES CATGO(CATGO_CODE),
   PRODUCT_NAME VARCHAR2(50),
   PRODUCT_PRICE NUMBER,
   PRODUCT_CONTENT VARCHAR2(500),
   PRODUCT_TAG VARCHAR2(100),
   PRODUCT_DATE DATE,
   PRODUCT_LIKE NUMBER
);
alter table PRODUCT add constraint PRODUCT_PK1 primary key(PRODUCT_CODE);
create sequence PRODUCT_SEQ increment by 1 start with 1 nocache;

/* 상품사진 */
create table PRODUCT_PIC(
	PRODUCT_IDX NUMBER,
	PRODUCT_CODE NUMBER CONSTRAINT PRODUCT_PIC_FK REFERENCES PRODUCT(PRODUCT_CODE),
	PRODUCT_PIC_FNAME VARCHAR2(300),
	PRODUCT_PIC_OFNAME VARCHAR2(300),
	PRODUCT_PIC_FSIZE NUMBER
);
alter table PRODUCT_PIC add constraint PRODUCT_PIC_PK primary key(PRODUCT_IDX);
create sequence PRODUCT_PIC_SEQ increment by 1 start with 1 nocache;

/* 주문 */
create table ORDERLIST(
	ORDER_CODE NUMBER,
	MEMBER_NUMBER NUMBER(6) CONSTRAINT ORDER_FK1 REFERENCES MEMBER(MEMBER_NUMBER),
	PRODUCT_CODE NUMBER	  CONSTRAINT ORDER_FK2 REFERENCES PRODUCT(PRODUCT_CODE)
);
alter table ORDERLIST add constraint ORDERLIST_PK primary key(ORDER_CODE);
create sequence ORDERLIST_SEQ increment by 1 start with 1 nocache;

/* 찜한목록 */
create table LIKELIST(
   MEMBER_NUMBER NUMBER(6) CONSTRAINT LIKE_FK1 REFERENCES MEMBER(MEMBER_NUMBER),
   PRODUCT_CODE NUMBER CONSTRAINT LIKE_FK2 REFERENCES PRODUCT(PRODUCT_CODE)
);
alter table LIKELIST add constraint LIKE_PK primary key(MEMBER_NUMBER);

/* 장바구니 */
create table CART(
   CART_CODE NUMBER,
   PRODUCT_CODE NUMBER,
   MEMBER_NUMBER NUMBER(6),
   CONSTRAINT CART_PK PRIMARY KEY (CART_CODE)
);
create sequence CART_SEQ increment by 1 start with 1 nocache;

/* 결제 */
create table PAY(
   PAY_NUMBER NUMBER,
   ORDER_CODE NUMBER CONSTRAINT PAY_FK1 REFERENCES ORDERLIST(ORDER_CODE),
   PAY_DATE NUMBER,
   PAY_TOTALPAY VARCHAR2(20),
   PAY_METHOD VARCHAR2(30),
   PAY_BANK VARCHAR2(30),
   PAY_ADDRESS VARCHAR2(30),
   PAY_STATUS VARCHAR2(10)
);
alter table PAY add constraint PAY_PK primary key(PAY_NUMBER);
create sequence PAY_SEQ increment by 1 start with 1 nocache;


/* 산책 */
create table WALK(
	WALK_IDX NUMBER,
	MEMBER_NUMBER NUMBER(6) CONSTRAINT WALK_FK REFERENCES MEMBER(MEMBER_NUMBER),
	WALK_WRITER VARCHAR2(20),
	WALK_TYPE VARCHAR2(20),
	WALK_SUBJECT VARCHAR2(40),
	WALK_CONTENT VARCHAR2(3000),
	WALK_RDATE DATE,
	WALK_COUNT NUMBER,
	WALK_LOCATION VARCHAR2(30),
	WALK_DATE DATE
);
create sequence WALK_SEQ increment by 1 start with 1 nocache;
alter table WALK add constraint WALK_PK primary key(WALK_IDX);

/* 산책사진 */
create table WALK_PIC(
	WALK_PIC_IDX NUMBER,
	WALK_IDX NUMBER CONSTRAINT WALK_PIC_FK REFERENCES WALK(WALK_IDX),
	WALK_FNAME VARCHAR2(300),
	WALK_OFNAME VARCHAR2(300),
	WALK_FSIZE NUMBER
);
create sequence WALK_PIC_SEQ increment by 1 start with 1 nocache;
alter table WALK_PIC add constraint WALK_PIC_PK primary key(WALK_PIC_IDX);

/* 산책댓글 */
create table WALK_CMT(
	WALK_CMT_IDX NUMBER,
	WALK_IDX NUMBER CONSTRAINT WALK_CMT_FK REFERENCES WALK(WALK_IDX),
	WALK_CMT_WRITER VARCHAR2(20),
	WALK_CMT_CONTENT VARCHAR2(1000),
	WALK_CMT_DATE DATE
);
create sequence WALK_CMT_SEQ increment by 1 start with 1 nocache;
alter table WALK_CMT add constraint WALK_CMT_PK primary key(WALK_CMT_IDX);

/* 산책참가자 */
create table WALK_JOIN(
	WALK_IDX NUMBER constraint WALK_JOIN_FK1 REFERENCES WALK(WALK_IDX),
	MEMBER_NUMBER number(6) constraint WALK_JOIN_FK2 REFERENCES MEMBER(MEMBER_NUMBER)
);
alter table WALK_JOIN add constraint WALK_JOIN_PK primary key(WALK_IDX);

/* 산책태그 */
create table WALK_TAG(
	WALK_IDX NUMBER CONSTRAINT WALK_TAG_FK1 REFERENCES WALK(WALK_IDX),
	WALK_TAG VARCHAR2(30)
);
alter table WALK_TAG add constraint WALK_TAG_PK primary key(WALK_IDX);



/* 게시판 종류 구분 */
create table BOARD_SEP(
	BOARD_IDX NUMBER,
	BOARD_NAME VARCHAR2(30)
);
alter table BOARD_SEP add constraint BOARD_SEP_PK primary key(BOARD_IDX);

/* 게시판 */
create table BOARD(
	POST_IDX NUMBER,
	BOARD_IDX NUMBER CONSTRAINT BOARD_FK1 REFERENCES BOARD_SEP(BOARD_IDX),
	MEMBER_NUMBER NUMBER(6) CONSTRAINT BOARD_FK2 REFERENCES MEMBER(MEMBER_NUMBER),
	POST_WRITER VARCHAR2(20),
	POST_SUBJECT VARCHAR2(40),
	POST_CONTENT VARCHAR2(3000),
	POST_DATE DATE,
	POST_COUNT NUMBER,
	POST_LIKE NUMBER
);
create sequence BOARD_SEQ increment by 1 start with 1 nocache;
alter table BOARD add constraint POST_PK primary key(POST_IDX);

/* 게시판사진 */
create table BOARD_PIC(
	POST_IDX NUMBER CONSTRAINT BOARD_PIC_FK1 REFERENCES BOARD(POST_IDX),
	BOARD_IDX NUMBER CONSTRAINT BOARD_PIC_FK2 REFERENCES BOARD_SEP(BOARD_IDX),
	BOARD_PIC_FNAME VARCHAR2(300),
	BOARD_PIC_OFNAME VARCHAR2(300),
	BOARD_PIC_FSIZE number
);

/* 게시판태그 */
create table TAG(
	POST_IDX NUMBER CONSTRAINT TAG_FK1 REFERENCES BOARD(POST_IDX),
	BOARD_IDX NUMBER CONSTRAINT TAG_FK2 REFERENCES BOARD_SEP(BOARD_IDX),
	POST_TAG VARCHAR2(30)
);

/* 게시판댓글 */
create table BOARD_CMT(
	COMMENT_IDX NUMBER,
	POST_IDX NUMBER CONSTRAINT BOARD_CMT_FK1 REFERENCES BOARD(POST_IDX),
	BOARD_IDX NUMBER CONSTRAINT BOARD_CMT_FK2 REFERENCES BOARD_SEP(BOARD_IDX),
	MEMBER_NUMBER number(6) CONSTRAINT BOARD_CMT_FK3 REFERENCES MEMBER(MEMBER_NUMBER),
	CMT_CONTENT VARCHAR2(1000),
	CMT_WRITER VARCHAR2(20),
	CMT_DATE DATE
);
create sequence BOARD_CMT_SEQ increment by 1 start with 1 nocache;
